CSM_homepage:
    pattern:  /
    defaults: { _controller: CoralScrumMainBundle:Home:index }


# --- Project

CoralScrumMainBundle_project:
    resource: "@CoralScrumMainBundle/Resources/config/routing/project.yml"
    prefix:   /project


# --- Project Collaborator

CoralScrumMainBundle_collaborator:
    resource: "@CoralScrumMainBundle/Resources/config/routing/userproject.yml"
    prefix:   /project/{projectId}/collaborator


# --- Project / Sprint

CoralScrumMainBundle_sprint:
    resource: "@CoralScrumMainBundle/Resources/config/routing/sprint.yml"
    prefix:   /project/{projectId}/sprint


# --- Project / Task

CoralScrumMainBundle_task:
    resource: "@CoralScrumMainBundle/Resources/config/routing/task.yml"
    prefix:   /project/{projectId}/sprint/{sprintId}/task


# --- Project / Test

CoralScrumMainBundle_test:
    resource: "@CoralScrumMainBundle/Resources/config/routing/test.yml"
    prefix:   /project/{projectId}/test


# --- Project / UserStory

CoralScrumMainBundle_userstory:
    resource: "@CoralScrumMainBundle/Resources/config/routing/userstory.yml"
    prefix:   /project/{projectId}/userstory

