parameters:
#    coral_scrum_main.example.class: CoralScrum\MainBundle\Example

services:
#    coral_scrum_main.example:
#        class: %coral_scrum_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
