sprint:
    pattern:  /
    defaults: { _controller: "CoralScrumMainBundle:Sprint:index" }

sprint_show:
    pattern:  /{sprintId}/show
    defaults: { _controller: "CoralScrumMainBundle:Sprint:show" }

sprint_stats:
    pattern:  /{sprintId}/stats
    defaults: { _controller: "CoralScrumMainBundle:Sprint:stats" }

sprint_new:
    pattern:  /new
    defaults: { _controller: "CoralScrumMainBundle:Sprint:new" }

sprint_create:
    pattern:  /create
    defaults: { _controller: "CoralScrumMainBundle:Sprint:create" }
    requirements: { _method: post }

sprint_edit:
    pattern:  /{sprintId}/edit
    defaults: { _controller: "CoralScrumMainBundle:Sprint:edit" }

sprint_update:
    pattern:  /{sprintId}/update
    defaults: { _controller: "CoralScrumMainBundle:Sprint:update" }
    requirements: { _method: post|put }

sprint_delete:
    pattern:  /{sprintId}/delete
    defaults: { _controller: "CoralScrumMainBundle:Sprint:delete" }
    requirements: { _method: post|delete }
